version: '3.0'
services:
  web1:
    build:
      context: web1
      dockerfile: Dockerfile
    restart: on-failure
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "8080:80" # http
      #- "443:443" # https
  web2:
    build:
      context: web2
      dockerfile: Dockerfile
    restart: on-failure
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "8081:80" # http
      #- "443:443" # https      
